### ISSUE TITLE
Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by pepzwee** [schroffl/alfred-teamspeak#1]
```
TypeError: Class constructors cannot be invoked without 'new'
    at /var/node_servers/alfred/node_modules/alfred-teamspeak/index.js:8:13
    at Object.<anonymous> (/var/node_servers/alfred/bot.js:1:100)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

Tried with:
node v5.9.0
node v4.2.6

**Comment by schroffl** [comment]
This looks like an error with your code to me, would you mind sending it?

**Comment by pepzwee** [comment]
https://gist.github.com/Netifriik/8e9b184b645b6a076d2b

**Comment by schroffl** [comment]
The first few lines of your code should be:

``` javascript
var Alfred = require('alfred-teamspeak');
var bot = new Alfred( [...] );
```

which is equivalent to (what you tried to do):

``` javascript
var bot = new (require('alfred-teamspeak'))();
```

But I suggest you to just use the first method.
